### ISSUE TITLE
Package doesn't seem to be python3 compliant

### ISSUE THREAD

**Issue by labeneator** [manuthu/httpie-http-signatures#3]
I have attempted to install this package on a py3 environment and I think that it's dependency: httpsig_cffi.sign.HeaderSigner->generate_message is not outputting the correct signature in py3.

Additionally, the sign body block for POST & PUT is not py3 compatible (it concats bytes & strings). Here's the correct block

```python
 55         if sign_body:
 56             body = request.body or ""
 57             if "digest" not in request.headers:
 58                 m = hashlib.sha256(body.encode("utf-8"))
 59                 base64digest = base64.b64encode(m.digest())
 60                 base64string = base64digest.decode("utf-8")
 61                 request.headers["digest"] = 'SHA-256=' + base64string
```

**Comment by labeneator** [comment]
@manuthu Bump...

**Comment by manuthu** [comment]
Thanks for the pr. Just merged it
